# Generated by Django 5.2.3 on 2025-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_job_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='screenshots_data',
            field=models.TextField(blank=True, help_text='JSON data for interview screenshots', null=True),
        ),
    ]
