# Generated by Django 5.2.3 on 2025-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_interview_screenshots_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('maybe', 'Maybe'), ('not_recommended', 'Not Recommended'), ('never_hire', 'Never Hire')], help_text='AI recommendation for hiring', max_length=20, null=True),
        ),
    ]
