# Generated by Django 5.2.3 on 2025-11-21 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_interview_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('passcode', models.CharField(blank=True, help_text='Passcode for additional participants', max_length=8)),
                ('max_participants', models.IntegerField(default=5, help_text='Maximum number of participants')),
                ('enable_recording', models.BooleanField(default=True)),
                ('enable_screen_share', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_room', to='jobapp.interview')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('candidate', 'Candidate'), ('ai', 'AI Interviewer'), ('recruiter', 'Recruiter'), ('observer', 'Observer'), ('guest', 'Guest')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('peer_id', models.CharField(blank=True, max_length=100)),
                ('is_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('screen_sharing', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jobapp.interviewroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
